### PR TITLE
fix: fixed date cloning

### LINKED ISSUE #272: bug: `Date` parsing in `deepClone`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

There is a critical bug in `deepClone` in `@sapphire/utilities` (which then also affects `mergeDefault`) where it is incapable of parsing dates. Instead of duplicating the Date, it assigns the current date.

### Steps To Reproduce

```js
const { deepClone } = require('@sapphire/utilities');

const originalObject = { dateTime: new Date('2020-01-01T12:45:00.000Z') };

const clonedObject = deepClone(originalObject);

console.log(obj);
// { dateTime: 2020-01-01T12:45:00.000Z }

console.log(clonedObject);
// { dateTime: 2022-01-26T23:31:03.734Z }
```

Not the same date!

### Expected behavior

The date has to be the same

### Screenshots

image

### Additional context

I discovered this when we ran into the bug with code at work

### PR DESCRIPTION
**Pull request by favna**
fixes #272

wew lad

### CODE REVIEW

File: packages/utilities/src/lib/deepClone.ts [hunk 1]
```diff
@@ -10,6 +10,12 @@ export function deepClone<T>(source: T): T {
 		return source;
 	}
 
+	if (source instanceof Date) {
+		const output = new (source.constructor as DateConstructor)(source.toISOString());
```
Comment (kyranet) [inline packages/utilities/src/lib/deepClone.ts:14]:
```suggestion
		const output = new (source.constructor as DateConstructor)(source);
```

**Review by kyranet — CHANGES_REQUESTED** [review]

**Review by kyranet — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by c43721 — APPROVED** [review]
