### PR TITLE
fix(PaginatedMessages): missing logic cases

### LINKED ISSUE #330: bug: isMessageButtonInteraction function in PaginatedMessages utils
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

```js
DiscordAPIError: Invalid Form Body components: Must be 5 or fewer in length.
```
I add 4 button actions to the `PaginatedMessage` but it parses them as `ContextMenu` instead of `Button`.

### Steps To Reproduce

1. Use `PaginatedMessage.setActions` method.
2. Set 4 other button actions with the `type: "BUTTON"`.
3. Set `includeDefaultAction` is `true`.
4. Run the `PaginatedMessage`.

### Expected behavior

`PaginatedMessage` will run normally with 5 default actions in the first action row. And your actions in the second row and a SelectMenu at the 3rd row.

### Screenshots

_No response_

### Additional context

```ts
export function isMessageButtonInteraction(
	interaction: InteractionButtonOptions | MessageSelectMenuOptions
): interaction is InteractionButtonOptions {
	return interaction.type === Constants.MessageComponentTypes.BUTTON;
}
```
The `InteractionButtonOptions` and `MessageSelectMenuOptions` is `ExcludeEnum` type so they accept all of those types: `"BUTTON" | "SELECT_MENU" | 2 | 3`
On the other hand, `Constants.MessageComponentTypes.BUTTON` return 2. So that means if the `interaction.type === "BUTTON"`, the function will return `false`.

### PR DESCRIPTION
**Pull request by Mzato0001**
Fixes #330

### CODE REVIEW

**Review by vladfrangu — DISMISSED** [review]

**Review by favna — APPROVED** [review]

File: packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts [hunk 1]
```diff
@@ -36,6 +36,7 @@ export function runsOnInteraction(
 export function actionIsButtonOrMenu(action: PaginatedMessageAction): action is PaginatedMessageActionButton | PaginatedMessageActionMenu {
 	return (
 		action.type === Constants.MessageComponentTypes.SELECT_MENU ||
+		action.type === "SELECT_MENU" ||
```
Comment (favna) [inline packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts:39]:
```suggestion
		action.type === 'SELECT_MENU' ||
```

File: packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts [hunk 2]
```diff
@@ -44,7 +45,7 @@ export function actionIsButtonOrMenu(action: PaginatedMessageAction): action is
 export function isMessageButtonInteraction(
 	interaction: InteractionButtonOptions | MessageSelectMenuOptions
 ): interaction is InteractionButtonOptions {
-	return interaction.type === Constants.MessageComponentTypes.BUTTON;
+	return interaction.type === Constants.MessageComponentTypes.BUTTON || interaction.type === "BUTTON";
```
Comment (favna) [inline packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts:48]:
```suggestion
	return interaction.type === Constants.MessageComponentTypes.BUTTON || interaction.type === 'BUTTON';
```

**Review by favna — CHANGES_REQUESTED** [review]

**Review by favna — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Comment by favna** [comment]
Released in v4.9.5
