### PR TITLE
fix: fixed bun compatibility for @sapphire/utilities

### LINKED ISSUE #702: bug: bun build `@sapphire/utilities`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Warning `bun build` due wildcard sideEffects in `@sapphire/utilities`

### Steps To Reproduce

Execute `bun build --target node src/index.ts --outdir dist/` in any project using `bun build --target node src/index.ts --outdir dist/`

### Expected behavior

Use explicit sideEffects so the build is optimized and the warning doesn't appear

### Screenshots

image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by favna**
resolves #702

---

I was lowkey considering keeping it back until the 7th because of reasons but I didn't want to bother keeping it on just 1 laptop lol

### CODE REVIEW

File: scripts/dynamic-side-effects.mjs [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+	new URL(`../packages/${packageName}/dist/esm`, import.meta.url),
+	/chunk-[A-Z0-9]+\.mjs(?!\.map)/
+)) {
+	const name = basename(file).replace(/\.ts$/, '');
+
+	sideEffects.unshift(`./dist/esm/${name}`);
+}
+
+const { default: packageJSON } = await import(`../packages/${packageName}/package.json`, {
+	assert: {
```
Comment (vladfrangu) [inline scripts/dynamic-side-effects.mjs:23]: Nowadays its with, not assert 👀

**Review by kyranet — CHANGES_REQUESTED** [review]
Shouldn't we call `yarn dynamic-side-effects` in the `build` script? At least so we can `yarn build` and `yarn link` then test the library without remembering to call the new script.

**Review by kyranet — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]
